name: test

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
        with:
          version: "0.12.13"
      - run: uv sync --extra dev --frozen
      - run: uv run black --check .
      - run: uv run ruff check .
      - run: uv run mypy
      - run: uv run pytest
      - run: shellcheck install.sh
